[bells]
	[bells.local.LOCAL] #locally connected bell
	pin = 18 #gpio pin on RPi
	active_low = false #is it active low?

	[bells.remote.REMOTE] #network bell
	remote_ip = "1.2.3.4"
	remote_port = 80
	remote_secret = "password"

[functions]
	[functions.RING]
	sequence = [2000]

	[functions.FIRE]
	sequence = [4000, 3000, 4000, 3000, 4000] #3 4000ms rings with 3000ms inbetween

[controlbuttons]
	[controlbuttons.23] #for button on pin 24
	function = "RING"
	affecting_bells = ["LOCAL", "REMOTE"]

	[controlbuttons.25] #for button on pin 25
	function = "FIRE"
	affecting_bells = ["LOCAL", "REMOTE"]

	[controlbuttons.26] #for button on pin 26
	function = "STOP" #internal function
	affecting_bells = ["LOCAL", "REMOTE"]